[project]
authors = ["Michael Hess <michaelhess17@yahoo.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mujoco_stability"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
ipykernel = "*"
mediapy = "*"
matplotlib = "*"

[pypi-dependencies]
jax = { version = "*", extras = ["cuda12"] }
mujoco = "*"
mujoco-mjx = "*"
brax = "*"
